<div id="header">
    <div class="container">
        <div id="header__logo">
            Open Charity
        </div>
        <div id="header__menu">
            <div class="list">
                <a href="#" class="item" id="header__menu__item_1">About Open Charity</a>
                <a href="#" class="item" id="header__menu__item_2">The Blog</a>
                <a href="#" class="button item" id="header__menu__item_3">Join Us</a>
            </div>
        </div>
    </div>
</div>
